import 'package:flutter/material.dart';

import 'page/alphabetScrollPage.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Alphabet Scroll List'),
      ),
      body: AlphabetScrollPage(
          onClickedItem: (item) {
            final snackBar = SnackBar(
                content: Text(
              'Clicked item $item',
              style: TextStyle(fontSize: 20),
            ));
            ScaffoldMessenger.of(context)
              ..removeCurrentSnackBar()
              ..showSnackBar(snackBar);
          },
          items: [
            "あ",
            "あいう",
            "い",
            "愛情",
            "ん",
            "ら",
            "Alphabets",
            "Amharic",
            "Amphibians",
            "Anatomy",
            "Bacteria",
            "Badness",
            "Bags",
            "Balancing",
            "Bald",
            "Baseball",
            "Basketball",
            "Baskets",
            "Bears",
            "Beasts",
            "Beauty",
            "Beetles",
            "Beggars",
            "Cakes",
            "Calming",
            "Canadian",
            "Censuring",
            "Cereals",
            "Cetaceans",
            "Cheeses",
            "Chemical",
            "Colours",
            "Commanding",
            "Commerce",
            "Communications",
            "Compassion",
            "Complaining",
            "Computing",
            "Cricket",
            "Crockery",
            "Crustaceans",
            "Crystallography",
            "Dances",
            "Danger",
            "Darkness",
            "Danish",
            "Deceiving",
            "Deer",
            "Deign",
            "Denying",
            "Desserts",
            "Diets",
            "Digging",
            "Directions",
            "Dirtiness",
            "Dislike",
            "Disputing",
            "Divination",
            "Dutch",
            "Dying",
            "Earthquakes",
            "Eating",
            "Eggheads",
            "Electricity",
            "Enclosing",
            "Engraving",
            "Entangling",
            "Envy",
            "Excellence",
            "Facial",
            "Falconry",
            "Fatigue",
            "Ferns",
            "Festivities",
            "Finnish",
            "Firearms",
            "Afrikaans",
            "Age",
            "Agitation",
            "Ailments",
            "Albanian",
            "Alchemy",
            "Algae",
            "Alkalis",
            "Alkaloids",
            "Alloys",
            "Fish",
            "Fishing",
            "Flowers",
            "Fools",
            "Football",
            "Footwear",
            "French",
            "Friends",
            "Geological",
            "German",
            "Giving",
            "Glassware",
            "Gossips",
            "Gymnastics",
            "Gypsies",
            "Habitations",
            "Happening",
            "Happiness",
            "Harming",
            "Hawaiian",
            "Headgear",
            "Hearing",
            "Hebrew",
            "Helping",
            "Heraldry",
            "Hiding",
            "Icelandic",
            "Impertinence",
            "Implements",
            "Intelligence",
            "Interjections",
            "Intriguing",
            "Inuktitut",
            "Irish",
            "Italian",
            "Itching",
            "Jams",
            "Javanese",
            "Jewelry",
            "Killing",
            "Kindred",
            "Korean",
            "Lagormorphs",
            "Lamps",
            "Lagormorphs",
            "Lamps",
            "Lagormorphs",
            "Lamps",
            "Magic",
            "Malagasy",
            "Malay",
            "Malayalam",
            "Maltese",
            "Maori",
            "Marathi",
            "Marine",
            "Metalwork",
            "Micro",
            "Military",
            "Ranks",
            "Minerals",
            "Miscellaneous",
            "Sport",
            "Misers",
            "Molluscs",
            "Nahuatl",
            "Names",
            "Native",
            "Neckwear",
            "Nepali",
            "Norwegian",
            "Nothing",
            "Old",
            "Old",
            "Optics",
            "Ornament",
            "Other",
            "Other",
            "Primates",
            "Printing",
            "Pronunciation",
            "Pseuds",
            "Psychiatry",
            "Psychology",
            "Punjabi",
            "Pushing",
            "Putting",
            "Puzzles",
            "Quechua",
            "Radicals",
            "Rubbish",
            "Rowing",
            "Rugby",
            "Rulers",
            "Russian",
            "Sailing",
            "Salads",
            "Sugars",
            "Surfing",
            "Surprise",
            "Swahili",
            "Sweating",
            "Swedish",
            "Swimming",
            "Swords",
            "Tagalog",
            "Tahitian",
            "Tamil",
            "Trees",
            "Truanting",
            "Trying",
            "Tumours",
            "Tupi",
            "Turkish",
            "Tylopods",
            "Underwear",
            "Urdu",
            "Vegetables",
            "Veterinary",
            "Vietnamese",
            "Viruses",
            "Vitality",
            "Vitamins",
            "Viverrids",
            "Vomiting",
            "Wanting",
            "Warmth",
            "Water",
            "Weaning",
            "Weapons",
            "Weaving",
            "Welsh",
            "Whatsits",
            "Wimps",
            "Winds",
            "Wolof",
            "Wood",
            "Wrestling",
            "XAAAA",
            "XBBB",
            "XCCC",
            "Yiddish",
            "Yoga",
            "Yoruba",
            "Young",
            "Animals",
            "Zulu"
          ]),
    );
  }
}
